name: CI

on:
  workflow_call:
    inputs:
      setupAntlr4:
        description: Set up Antlr4.
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  unit-tests:
    uses: siacodelabs/.github/github/workflows/nodets-ci.yaml@main
    with:
      setup-antlr4: true
